FORMAT: 1A
HOST: https://api.geokrety.org

# GeoKrety Server API

GeoKrety is an on-line tracking service targeted at Geocachers.
Each registered object, called a GeoKret (plural: GeoKrety),
has a unique tracking code, allowing its movements between locations
such as Geocaches to be tracked and registered on the service.

https://geokrety.org is an open source project started in 2007.
It is developped and maintained by a group of volunters.

Here you'll find the online documentation for the API behind the project.

If you find any bug please open issues on the project GitHub tracker https://github.com/GeoKrety/geokrety-api/issues.



::: warning
#### <i class="fa fa-warning"></i> Caution
This is **not yet the production service**. See https://geokrety.org/api.php for the current service API.
:::


# Data Structures


## `jsonapi` (object)
- `version`: `1.0` (string)

## `JSONAPI Error` (object) - JSONAPI Error
+ status: 422 (number, required)
+ source (object, required)
  + pointer: `/data/attributes/name` (string, required)
  + detail: `Username already taken` (string, required)
  + title: `Unprocessable Entity` (string, required)

## Error 401 (object) - HTTP Error 401
+ description: Authentication required (string, required)
+ error: Bad Request (string, required)
+ status_code: 401 (number, required)

## Error 403 (object) - HTTP Error 403
+ description: You don't have access to this ressource (string, required)
+ error: Access Forbidden (string, required)
+ status_code: 403 (number, required)

## Error 404 (object) - HTTP Error 404
+ description: This ressource does not exists (string, required)
+ error: Object Not Found (string, required)
+ status_code: 404 (number, required)

## Error 422 (object) - JSONAPI HTTP Error 422
+ errors (array[JSONAPI Error], required)
+ jsonapi (jsonapi, required)



## Deleted (object) - Object successfully deleted
+ meta (object, required)
    + message: Object successfully deleted (string, required)
+ jsonapi (jsonapi, required)


## User Public (object)
+ name: Boba Fett (string, required) - User name
+ language: fr (string, optional) - User spoken language
+ country: fr (string, optional) - User home country
    + Default: Country derived from user home coordinates
+ `join-date-time`: `2017-01-14T22:57:44` (string, required) - Joining date
    + Default: now

## User (User Public)
+ `statpic-id`: 4 (number, required) - Statpic template id
    + Default: 0
+ email: ser@ema.il (string, required) - User mail address
+ `daily-mail`: true (boolean, required) - `True` if the user want to receive daily digest
    + Default: true
+ latitude: 48.86471 (number, optional) - Home latitude (Home location)
+ longitude: 2.34901 (number, optional) - Home longitude (Home location)
+ `observation-radius`: 7 (string, required) - How far from home location to look for moves
+ hour: 7 (string, required) - Send mail at this hour
+ `last-update-date-time`: `2017-01-26T19:46:44` (string, required) - Date of last account update
+ `last-mail-date-time`: `2017-03-29T07:52:02` (string, required) - Date of last sent mail (daily mail)
+ `last-login-date-time`: `2017-09-14T22:04:05` (string, required) - Date of last login
+ secid: abc123 (string, optional) - User secret id for legacy API

## News (object)
+ title: New doc online (string, required) - The news title
+ content: Hi guys, the news API documentation is now available online. See Github page... (string, required) - The news text
+ username: someone (string, optional) - Override author username

## News Comment (object)
+ comment: New API is really nice!!! (string, required) - The user posted comment
+ icon: 0 (number, required) - Icon template `id` illustrating the comment
+ created-on-date-time: 2017-09-15T08:12:10 (string, required) - Creation date time
+ author (User) - Author of the news comment post.
+ news (News) - News which was commented.

## RelationshipsAuthor (object)
+ author (object)
    + data (object)
        + type: user (string, fixed-type, required)
        + id: 26422 (string, required) - User id

## RelationshipsNewsComment (object)
+ news-comments (object)
    + data (object)
        + type: news-comment (string, fixed-type, required)
        + id: 806 (string, required) - News comment id



<!-- include(authentication.apib) -->
<!-- include(users.apib) -->
<!-- include(news.apib) -->
<!-- include(news-comments.apib) -->
