# Group Moves Types
Resources related to GeoKrety in the API.

---

**Moves Types endpoints permissions:**

| Privilege level     | List    | View    | Create  | Update  | Delete  |
|:--------------------|---------|---------|---------|---------|---------|
| Anonymous           | ✓       | ✓       | ✗       | ✗       | ✗       |
| Authenticated       | ✓       | ✓       | ✗       | ✗       | ✗       |
| Administrators      | ✓       | ✓       | ✓       | ✓       | ✓       |

---

**Moves Types attributes:**

| Parameter                | Description                               | Type    | Required | Readonly | Public  |
|:-------------------------|-------------------------------------------|---------|----------|----------|---------|
| `name`                   | Moves Type name                           | string  | **yes**  | -        | **yes** |

---

**Moves Types:**

| Type       | Description   | Require waypoint | Require Tracking-Code |
|:-----------|---------------|------------------|-----------------------|
| `0`        | Dropped to    | **yes**          | **yes**               |
| `1`        | Grabbed from  | -                | **yes**               |
| `2`        | A comment     | -                | -                     |
| `3`        | Seen in       | **yes**          | **yes**               |
| `4`        | Archived      | -                | **yes**               |
| `5`        | Visiting      | **yes**          | **yes**               |

---

**Moves Types Relations:**

| Parameter       | Type         | Description                           |
|:----------------|--------------|---------------------------------------|
| `move`          | moves        | Moves which are of the type            |

---

## Moves Type Details [/v1/moves-types/{moves_types_id}]

+ Parameters
    + moves_types_id: 1 (string) - ID of the Moves Types.

### Get Moves Type [GET]


+ Request

    + Headers

            Authorization: JWT <Auth Key>
            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Attributes (object)
        + `data` (moves-types-data, required)
        + `jsonapi` (jsonapi, required)
        + `links` (object, required)
            + `self`: `/moves-types`

+ Response 404 (application/json)

    + Attributes (Error 404)


### Update Moves Type [PATCH]
Update a single Moves Type by `id`.


+ Request

    + Headers

            Authorization: JWT <Auth Key>
            Content-Type: application/vnd.api+json


    + Attributes (object)
        + `data` (moves-types-data-type, required)
          + `attributes` (moves-types-attributes)

+ Response 200 (application/vnd.api+json)

    + Attributes (object)
        + `data` (moves-types-data, required)
        + `jsonapi` (jsonapi, required)
        + `links` (object, required)
            + `self`: `/moves-types`

+ Response 401 (application/json)

    + Attributes (Error 401)

+ Response 403 (application/json)

    + Attributes (Error 403)

+ Response 404 (application/json)

    + Attributes (Error 404)



### Delete Moves Type [DELETE]

::: warning
#### <i class="fa fa-warning"></i> Caution
This will delete **all** GeoKrety of that type, including logs, comments and pictures.
:::

+ Request

    + Headers

            Authorization: JWT <Auth Key>
            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Attributes (Deleted, required)

+ Response 403 (application/json)

    + Attributes (Error 403)

+ Response 404 (application/json)

    + Attributes (Error 404)


## GeoKrety Collection [/v1/moves-types{?page%5Bsize%5D,page%5Bnumber%5D,sort,filter}]


### Create a Moves Type [POST]

+ Request

    + Attributes (object)
        + `attributes` (moves-types-attributes)

    + Headers

            Authorization: JWT <Auth Key>
            Content-Type: application/vnd.api+json
            Accept: application/vnd.api+json

+ Response 201 (application/vnd.api+json)

    + Attributes (object)
        + `data` (moves-types-data, required)
        + `jsonapi` (jsonapi, required)
        + `links` (object, required)
            + `self`: `/moves-types`


### List all Moves Type [GET]
Retrieve paginated list of Moves Type.

+ Parameters
    + page%5Bsize%5D (optional, integer, `10`) - Maximum number of resources in a single paginated response.
    + page%5Bnumber%5D (optional, integer, `2`) - Page number to be fetched for the paginated response.
    + sort (optional, string, `created-on-date-time`) - Sort the resources according to the given attribute in ascending order. Append '-' to sort in descending order.
    + filter (optional, string, ``) - Filter according to the flask-rest-jsonapi filtering system. Please refer: http://flask-rest-jsonapi.readthedocs.io/en/latest/filtering.html for more.


+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Attributes (object)
        + `meta` (meta, required)
        + `data` (array[moves-types-data])
        + `jsonapi` (jsonapi, required)
        + `links` (object, required)
            + `self`: `/moves-types`



# Data Structures

## `moves-types-data-type` (object)
- `type`: `geokrety-type` (string, required)
- `id`: `1` (string, required)

## `moves-types-links` (object)
- `self`: `/moves-types/1` (string, required)

## `moves-types-related` (object)
- `related`: `/moves-types/1` (string, required)

## `moves-types-attributes` (object)
- `name`: `Traditional` (string, required)

## `moves-types-geokrety` (object)
- `links` (geokrety-related)
  - `self`: `/moves-types/1/relationships/geokrety` (string)

## `moves-types-relationships` (object)
- `geokrety` (moves-types-geokrety)

## `moves-types-data` (moves-types-data-type)
- `attributes` (moves-types-attributes, required)
- `relationships` (moves-types-relationships, optional)
- `links` (moves-types-links, required)
